from os import system
system('sudo apt-get update -y')
system('clear')
system('sudo apt-get upgarde -y')
system('clear')
system('sudo apt-get dist-upgrade -y')
system('clear')
system('sudo apt-get install python && apt-get install python3 && apt-get install python3-pip -y')
system('clear')
system('sudo apt install snapd -y')
system('clear')
system('sudo apt-get install telegram-desktop -y')
system('clear')
system('sudo apt install kazam -y')
system('clear')
system('sudo apt install vokoscreen -y')
system('clear')
system('wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -')
system('clear')
system('sudo apt-get install apt-transport-https')
system('clear')
system('echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list')
system('clear')
system('echo "deb https://download.sublimetext.com/ apt/dev/" | sudo tee /etc/apt/sources.list.d/sublime-text.list')
system('clear')
system('sudo apt-get install sublime-text -y')
system('clear')